# Generated by Django 3.1.2 on 2022-04-02 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoLists',
            fields=[
                ('todoID', models.AutoField(primary_key=True, serialize=False)),
                ('todoName', models.CharField(max_length=100)),
                ('UserID', models.IntegerField()),
                ('todoDescription', models.TextField()),
                ('todoStatus', models.BooleanField(default=False)),
                ('DateCompleted', models.DateField()),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('DateUpdated', models.DateTimeField(auto_now=True)),
                ('UserName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'UserName',
            },
        ),
    ]
